language: ruby
rvm:
  - 2.1.2

env:
  THREE_TAPS_API_KEY="nzzO9KcH4XUAJMcsPinqZ+IzKiedKxRHMrivAbwMXqGAhyfSM/0TrOsKN8uKrVlFBzM4uBOt3T275+8xoP9jS9kk3eHMMxcnuoDJgA/afURHZfpfkQlOjFJiJ2r6W5fNjy+Zgh6b0wbNayw+OpuIFPto4BDXROcU+QgmsZDIfCW0VTcE/Y+eMFYVB22nDblk3nCP+Qy1p8hOzrzjBiKLVMD1TF/1UCBeyixMRokRgK+CyIadftV5qktOD6koadEK8e39zd0gW4GUAlVyL93QrNDuXeO7Zdy0yn7jUYbrB3TzNYXBsAob1F2JmmfEdfp9c9BEjwqBUF/rY8gfoiM+WCILCpL6CIgdc2RSFIMKe9ReGAa7Zgc+RJJ7qj2J0bAh7B3+El4Tf6YL1s3rTmGnNYHA6QzSJgGpKzNF0zFKMDFiqvfk4nFbyrdB/QBBtCEACD79eIryVeh1qwJgrLn0oRlQWTwBIydNBYX1qdKA2Sjnv36PD5poU6kSZFXvRyd1umrA+dE6IgmDuf28n/I+qdBvmsBKsHI7RnzQD1KHjFUes/IJJorbN3aMYtmtQAVJw3icpgOpdTA0YyhNShK559RRY2jZFauxEHVNPpawSMu4goVmofTjqt0tYm6yV52qQkHDULWcbc4Gyzwp/3llWR2c/oYfwBuN46hnU1+G5Vk="


